version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "27017:27017"

  backend:
    image: openjdk:23
    container_name: spring-backend
    volumes:
      - ./target/ditos-0.0.1-SNAPSHOT.jar:/app.jar
    command: ["java", "-jar", "/app.jar"]
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: ${MONGO_DB}
      JWT_SECRET: ${JWT_SECRET}
      APP_ADMIN_USER: ${APP_ADMIN_USER}
      APP_ADMIN_PASSWORD: ${APP_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - mongo